/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alias Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.AliasRule#getPlatform <em>Platform</em>}</li>
 *   <li>{@link ecs.lang.AliasRule#getTypeAlias <em>Type Alias</em>}</li>
 *   <li>{@link ecs.lang.AliasRule#getSize <em>Size</em>}</li>
 *   <li>{@link ecs.lang.AliasRule#isVariableSize <em>Variable Size</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getAliasRule()
 * @model
 * @generated
 */
public interface AliasRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Platform</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Platform</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Platform</em>' reference.
   * @see #setPlatform(PlatformID)
   * @see ecs.lang.LangPackage#getAliasRule_Platform()
   * @model
   * @generated
   */
  PlatformID getPlatform();

  /**
   * Sets the value of the '{@link ecs.lang.AliasRule#getPlatform <em>Platform</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Platform</em>' reference.
   * @see #getPlatform()
   * @generated
   */
  void setPlatform(PlatformID value);

  /**
   * Returns the value of the '<em><b>Type Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Alias</em>' attribute.
   * @see #setTypeAlias(String)
   * @see ecs.lang.LangPackage#getAliasRule_TypeAlias()
   * @model
   * @generated
   */
  String getTypeAlias();

  /**
   * Sets the value of the '{@link ecs.lang.AliasRule#getTypeAlias <em>Type Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Alias</em>' attribute.
   * @see #getTypeAlias()
   * @generated
   */
  void setTypeAlias(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see ecs.lang.LangPackage#getAliasRule_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link ecs.lang.AliasRule#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

  /**
   * Returns the value of the '<em><b>Variable Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable Size</em>' attribute.
   * @see #setVariableSize(boolean)
   * @see ecs.lang.LangPackage#getAliasRule_VariableSize()
   * @model
   * @generated
   */
  boolean isVariableSize();

  /**
   * Sets the value of the '{@link ecs.lang.AliasRule#isVariableSize <em>Variable Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable Size</em>' attribute.
   * @see #isVariableSize()
   * @generated
   */
  void setVariableSize(boolean value);

} // AliasRule
