/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Api Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.ApiRule#getComponent <em>Component</em>}</li>
 *   <li>{@link ecs.lang.ApiRule#getAccesors <em>Accesors</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getApiRule()
 * @model
 * @generated
 */
public interface ApiRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Component</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' reference.
   * @see #setComponent(AComponent)
   * @see ecs.lang.LangPackage#getApiRule_Component()
   * @model
   * @generated
   */
  AComponent getComponent();

  /**
   * Sets the value of the '{@link ecs.lang.ApiRule#getComponent <em>Component</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component</em>' reference.
   * @see #getComponent()
   * @generated
   */
  void setComponent(AComponent value);

  /**
   * Returns the value of the '<em><b>Accesors</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Accesors</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accesors</em>' attribute list.
   * @see ecs.lang.LangPackage#getApiRule_Accesors()
   * @model unique="false"
   * @generated
   */
  EList<String> getAccesors();

} // ApiRule
