/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ASystem</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ecs.lang.LangPackage#getASystem()
 * @model
 * @generated
 */
public interface ASystem extends EObject
{
} // ASystem
