/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.ComponentAlias#isUnique <em>Unique</em>}</li>
 *   <li>{@link ecs.lang.ComponentAlias#getContextRef <em>Context Ref</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getComponentAlias()
 * @model
 * @generated
 */
public interface ComponentAlias extends EObject
{
  /**
   * Returns the value of the '<em><b>Unique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unique</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique</em>' attribute.
   * @see #setUnique(boolean)
   * @see ecs.lang.LangPackage#getComponentAlias_Unique()
   * @model
   * @generated
   */
  boolean isUnique();

  /**
   * Sets the value of the '{@link ecs.lang.ComponentAlias#isUnique <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unique</em>' attribute.
   * @see #isUnique()
   * @generated
   */
  void setUnique(boolean value);

  /**
   * Returns the value of the '<em><b>Context Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Ref</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Ref</em>' containment reference.
   * @see #setContextRef(ContextReference)
   * @see ecs.lang.LangPackage#getComponentAlias_ContextRef()
   * @model containment="true"
   * @generated
   */
  ContextReference getContextRef();

  /**
   * Sets the value of the '{@link ecs.lang.ComponentAlias#getContextRef <em>Context Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Ref</em>' containment reference.
   * @see #getContextRef()
   * @generated
   */
  void setContextRef(ContextReference value);

} // ComponentAlias
