/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.ContextDefinition#getNames <em>Names</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getContextDefinition()
 * @model
 * @generated
 */
public interface ContextDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Names</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.ContextName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Names</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Names</em>' containment reference list.
   * @see ecs.lang.LangPackage#getContextDefinition_Names()
   * @model containment="true"
   * @generated
   */
  EList<ContextName> getNames();

} // ContextDefinition
