/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.CreateRule#getName <em>Name</em>}</li>
 *   <li>{@link ecs.lang.CreateRule#getComponentTypes <em>Component Types</em>}</li>
 *   <li>{@link ecs.lang.CreateRule#getContextRef <em>Context Ref</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getCreateRule()
 * @model
 * @generated
 */
public interface CreateRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ecs.lang.LangPackage#getCreateRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ecs.lang.CreateRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Component Types</b></em>' reference list.
   * The list contents are of type {@link ecs.lang.AComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Types</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Types</em>' reference list.
   * @see ecs.lang.LangPackage#getCreateRule_ComponentTypes()
   * @model
   * @generated
   */
  EList<AComponent> getComponentTypes();

  /**
   * Returns the value of the '<em><b>Context Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Ref</em>' reference.
   * @see #setContextRef(ContextName)
   * @see ecs.lang.LangPackage#getCreateRule_ContextRef()
   * @model
   * @generated
   */
  ContextName getContextRef();

  /**
   * Sets the value of the '{@link ecs.lang.CreateRule#getContextRef <em>Context Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Ref</em>' reference.
   * @see #getContextRef()
   * @generated
   */
  void setContextRef(ContextName value);

} // CreateRule
