/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.InputTrigger#getEnterComponents <em>Enter Components</em>}</li>
 *   <li>{@link ecs.lang.InputTrigger#getLeft <em>Left</em>}</li>
 *   <li>{@link ecs.lang.InputTrigger#getEnteredOrLeft <em>Entered Or Left</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getInputTrigger()
 * @model
 * @generated
 */
public interface InputTrigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Enter Components</b></em>' reference list.
   * The list contents are of type {@link ecs.lang.AComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enter Components</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enter Components</em>' reference list.
   * @see ecs.lang.LangPackage#getInputTrigger_EnterComponents()
   * @model
   * @generated
   */
  EList<AComponent> getEnterComponents();

  /**
   * Returns the value of the '<em><b>Left</b></em>' reference list.
   * The list contents are of type {@link ecs.lang.AComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' reference list.
   * @see ecs.lang.LangPackage#getInputTrigger_Left()
   * @model
   * @generated
   */
  EList<AComponent> getLeft();

  /**
   * Returns the value of the '<em><b>Entered Or Left</b></em>' reference list.
   * The list contents are of type {@link ecs.lang.AComponent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entered Or Left</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entered Or Left</em>' reference list.
   * @see ecs.lang.LangPackage#getInputTrigger_EnteredOrLeft()
   * @model
   * @generated
   */
  EList<AComponent> getEnteredOrLeft();

} // InputTrigger
