/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parent System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.ParentSystem#isComponentAlias <em>Component Alias</em>}</li>
 *   <li>{@link ecs.lang.ParentSystem#getParent <em>Parent</em>}</li>
 *   <li>{@link ecs.lang.ParentSystem#getChildren <em>Children</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getParentSystem()
 * @model
 * @generated
 */
public interface ParentSystem extends AComponent, ASystem
{
  /**
   * Returns the value of the '<em><b>Component Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Alias</em>' attribute.
   * @see #setComponentAlias(boolean)
   * @see ecs.lang.LangPackage#getParentSystem_ComponentAlias()
   * @model
   * @generated
   */
  boolean isComponentAlias();

  /**
   * Sets the value of the '{@link ecs.lang.ParentSystem#isComponentAlias <em>Component Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Alias</em>' attribute.
   * @see #isComponentAlias()
   * @generated
   */
  void setComponentAlias(boolean value);

  /**
   * Returns the value of the '<em><b>Parent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parent</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent</em>' reference.
   * @see #setParent(Alias)
   * @see ecs.lang.LangPackage#getParentSystem_Parent()
   * @model
   * @generated
   */
  Alias getParent();

  /**
   * Sets the value of the '{@link ecs.lang.ParentSystem#getParent <em>Parent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent</em>' reference.
   * @see #getParent()
   * @generated
   */
  void setParent(Alias value);

  /**
   * Returns the value of the '<em><b>Children</b></em>' reference list.
   * The list contents are of type {@link ecs.lang.ASystem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Children</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Children</em>' reference list.
   * @see ecs.lang.LangPackage#getParentSystem_Children()
   * @model
   * @generated
   */
  EList<ASystem> getChildren();

} // ParentSystem
