/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.Procedure#isComponentAlias <em>Component Alias</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getContextRef <em>Context Ref</em>}</li>
 *   <li>{@link ecs.lang.Procedure#isUnique <em>Unique</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getName <em>Name</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getParams <em>Params</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getUniqueComp <em>Unique Comp</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getGroups <em>Groups</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getIndex <em>Index</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getCreateRules <em>Create Rules</em>}</li>
 *   <li>{@link ecs.lang.Procedure#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getProcedure()
 * @model
 * @generated
 */
public interface Procedure extends EObject
{
  /**
   * Returns the value of the '<em><b>Component Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Alias</em>' attribute.
   * @see #setComponentAlias(boolean)
   * @see ecs.lang.LangPackage#getProcedure_ComponentAlias()
   * @model
   * @generated
   */
  boolean isComponentAlias();

  /**
   * Sets the value of the '{@link ecs.lang.Procedure#isComponentAlias <em>Component Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Alias</em>' attribute.
   * @see #isComponentAlias()
   * @generated
   */
  void setComponentAlias(boolean value);

  /**
   * Returns the value of the '<em><b>Context Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Ref</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Ref</em>' containment reference.
   * @see #setContextRef(ContextReference)
   * @see ecs.lang.LangPackage#getProcedure_ContextRef()
   * @model containment="true"
   * @generated
   */
  ContextReference getContextRef();

  /**
   * Sets the value of the '{@link ecs.lang.Procedure#getContextRef <em>Context Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Ref</em>' containment reference.
   * @see #getContextRef()
   * @generated
   */
  void setContextRef(ContextReference value);

  /**
   * Returns the value of the '<em><b>Unique</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unique</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique</em>' attribute.
   * @see #setUnique(boolean)
   * @see ecs.lang.LangPackage#getProcedure_Unique()
   * @model
   * @generated
   */
  boolean isUnique();

  /**
   * Sets the value of the '{@link ecs.lang.Procedure#isUnique <em>Unique</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unique</em>' attribute.
   * @see #isUnique()
   * @generated
   */
  void setUnique(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ecs.lang.LangPackage#getProcedure_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ecs.lang.Procedure#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see ecs.lang.LangPackage#getProcedure_Params()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParams();

  /**
   * Returns the value of the '<em><b>Unique Comp</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.UniqueComponentAccess}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unique Comp</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unique Comp</em>' containment reference list.
   * @see ecs.lang.LangPackage#getProcedure_UniqueComp()
   * @model containment="true"
   * @generated
   */
  EList<UniqueComponentAccess> getUniqueComp();

  /**
   * Returns the value of the '<em><b>Groups</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.Group}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Groups</em>' containment reference list.
   * @see ecs.lang.LangPackage#getProcedure_Groups()
   * @model containment="true"
   * @generated
   */
  EList<Group> getGroups();

  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.Index}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference list.
   * @see ecs.lang.LangPackage#getProcedure_Index()
   * @model containment="true"
   * @generated
   */
  EList<Index> getIndex();

  /**
   * Returns the value of the '<em><b>Create Rules</b></em>' containment reference list.
   * The list contents are of type {@link ecs.lang.CreateRule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Create Rules</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Create Rules</em>' containment reference list.
   * @see ecs.lang.LangPackage#getProcedure_CreateRules()
   * @model containment="true"
   * @generated
   */
  EList<CreateRule> getCreateRules();

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Alias)
   * @see ecs.lang.LangPackage#getProcedure_Type()
   * @model
   * @generated
   */
  Alias getType();

  /**
   * Sets the value of the '{@link ecs.lang.Procedure#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Alias value);

} // Procedure
