/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.SingleAlias#getTypeAlias <em>Type Alias</em>}</li>
 *   <li>{@link ecs.lang.SingleAlias#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getSingleAlias()
 * @model
 * @generated
 */
public interface SingleAlias extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Alias</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Alias</em>' attribute.
   * @see #setTypeAlias(String)
   * @see ecs.lang.LangPackage#getSingleAlias_TypeAlias()
   * @model
   * @generated
   */
  String getTypeAlias();

  /**
   * Sets the value of the '{@link ecs.lang.SingleAlias#getTypeAlias <em>Type Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Alias</em>' attribute.
   * @see #getTypeAlias()
   * @generated
   */
  void setTypeAlias(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see ecs.lang.LangPackage#getSingleAlias_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link ecs.lang.SingleAlias#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // SingleAlias
