/**
 * generated by Xtext 2.10.0
 */
package ecs.lang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unique Component Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.UniqueComponentAccess#getApiRule <em>Api Rule</em>}</li>
 *   <li>{@link ecs.lang.UniqueComponentAccess#getContextRef <em>Context Ref</em>}</li>
 * </ul>
 *
 * @see ecs.lang.LangPackage#getUniqueComponentAccess()
 * @model
 * @generated
 */
public interface UniqueComponentAccess extends EObject
{
  /**
   * Returns the value of the '<em><b>Api Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Api Rule</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Api Rule</em>' containment reference.
   * @see #setApiRule(ApiRule)
   * @see ecs.lang.LangPackage#getUniqueComponentAccess_ApiRule()
   * @model containment="true"
   * @generated
   */
  ApiRule getApiRule();

  /**
   * Sets the value of the '{@link ecs.lang.UniqueComponentAccess#getApiRule <em>Api Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Api Rule</em>' containment reference.
   * @see #getApiRule()
   * @generated
   */
  void setApiRule(ApiRule value);

  /**
   * Returns the value of the '<em><b>Context Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Ref</em>' reference.
   * @see #setContextRef(ContextName)
   * @see ecs.lang.LangPackage#getUniqueComponentAccess_ContextRef()
   * @model
   * @generated
   */
  ContextName getContextRef();

  /**
   * Sets the value of the '{@link ecs.lang.UniqueComponentAccess#getContextRef <em>Context Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Ref</em>' reference.
   * @see #getContextRef()
   * @generated
   */
  void setContextRef(ContextName value);

} // UniqueComponentAccess
