/**
 * generated by Xtext 2.10.0
 */
package ecs.lang.impl;

import ecs.lang.AComponent;
import ecs.lang.ApiRule;
import ecs.lang.Input;
import ecs.lang.InputTrigger;
import ecs.lang.LangPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link ecs.lang.impl.InputImpl#isUnqiue <em>Unqiue</em>}</li>
 *   <li>{@link ecs.lang.impl.InputImpl#getTriggers <em>Triggers</em>}</li>
 *   <li>{@link ecs.lang.impl.InputImpl#getEnsureComponents <em>Ensure Components</em>}</li>
 *   <li>{@link ecs.lang.impl.InputImpl#getExcludeComponents <em>Exclude Components</em>}</li>
 *   <li>{@link ecs.lang.impl.InputImpl#getApiRules <em>Api Rules</em>}</li>
 *   <li>{@link ecs.lang.impl.InputImpl#isDestroy <em>Destroy</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InputImpl extends MinimalEObjectImpl.Container implements Input
{
  /**
   * The default value of the '{@link #isUnqiue() <em>Unqiue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnqiue()
   * @generated
   * @ordered
   */
  protected static final boolean UNQIUE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isUnqiue() <em>Unqiue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isUnqiue()
   * @generated
   * @ordered
   */
  protected boolean unqiue = UNQIUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getTriggers() <em>Triggers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTriggers()
   * @generated
   * @ordered
   */
  protected EList<InputTrigger> triggers;

  /**
   * The cached value of the '{@link #getEnsureComponents() <em>Ensure Components</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnsureComponents()
   * @generated
   * @ordered
   */
  protected EList<AComponent> ensureComponents;

  /**
   * The cached value of the '{@link #getExcludeComponents() <em>Exclude Components</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExcludeComponents()
   * @generated
   * @ordered
   */
  protected EList<AComponent> excludeComponents;

  /**
   * The cached value of the '{@link #getApiRules() <em>Api Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApiRules()
   * @generated
   * @ordered
   */
  protected EList<ApiRule> apiRules;

  /**
   * The default value of the '{@link #isDestroy() <em>Destroy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDestroy()
   * @generated
   * @ordered
   */
  protected static final boolean DESTROY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isDestroy() <em>Destroy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDestroy()
   * @generated
   * @ordered
   */
  protected boolean destroy = DESTROY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LangPackage.Literals.INPUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isUnqiue()
  {
    return unqiue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUnqiue(boolean newUnqiue)
  {
    boolean oldUnqiue = unqiue;
    unqiue = newUnqiue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LangPackage.INPUT__UNQIUE, oldUnqiue, unqiue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<InputTrigger> getTriggers()
  {
    if (triggers == null)
    {
      triggers = new EObjectContainmentEList<InputTrigger>(InputTrigger.class, this, LangPackage.INPUT__TRIGGERS);
    }
    return triggers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AComponent> getEnsureComponents()
  {
    if (ensureComponents == null)
    {
      ensureComponents = new EObjectResolvingEList<AComponent>(AComponent.class, this, LangPackage.INPUT__ENSURE_COMPONENTS);
    }
    return ensureComponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AComponent> getExcludeComponents()
  {
    if (excludeComponents == null)
    {
      excludeComponents = new EObjectResolvingEList<AComponent>(AComponent.class, this, LangPackage.INPUT__EXCLUDE_COMPONENTS);
    }
    return excludeComponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ApiRule> getApiRules()
  {
    if (apiRules == null)
    {
      apiRules = new EObjectContainmentEList<ApiRule>(ApiRule.class, this, LangPackage.INPUT__API_RULES);
    }
    return apiRules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isDestroy()
  {
    return destroy;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDestroy(boolean newDestroy)
  {
    boolean oldDestroy = destroy;
    destroy = newDestroy;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, LangPackage.INPUT__DESTROY, oldDestroy, destroy));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case LangPackage.INPUT__TRIGGERS:
        return ((InternalEList<?>)getTriggers()).basicRemove(otherEnd, msgs);
      case LangPackage.INPUT__API_RULES:
        return ((InternalEList<?>)getApiRules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case LangPackage.INPUT__UNQIUE:
        return isUnqiue();
      case LangPackage.INPUT__TRIGGERS:
        return getTriggers();
      case LangPackage.INPUT__ENSURE_COMPONENTS:
        return getEnsureComponents();
      case LangPackage.INPUT__EXCLUDE_COMPONENTS:
        return getExcludeComponents();
      case LangPackage.INPUT__API_RULES:
        return getApiRules();
      case LangPackage.INPUT__DESTROY:
        return isDestroy();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case LangPackage.INPUT__UNQIUE:
        setUnqiue((Boolean)newValue);
        return;
      case LangPackage.INPUT__TRIGGERS:
        getTriggers().clear();
        getTriggers().addAll((Collection<? extends InputTrigger>)newValue);
        return;
      case LangPackage.INPUT__ENSURE_COMPONENTS:
        getEnsureComponents().clear();
        getEnsureComponents().addAll((Collection<? extends AComponent>)newValue);
        return;
      case LangPackage.INPUT__EXCLUDE_COMPONENTS:
        getExcludeComponents().clear();
        getExcludeComponents().addAll((Collection<? extends AComponent>)newValue);
        return;
      case LangPackage.INPUT__API_RULES:
        getApiRules().clear();
        getApiRules().addAll((Collection<? extends ApiRule>)newValue);
        return;
      case LangPackage.INPUT__DESTROY:
        setDestroy((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case LangPackage.INPUT__UNQIUE:
        setUnqiue(UNQIUE_EDEFAULT);
        return;
      case LangPackage.INPUT__TRIGGERS:
        getTriggers().clear();
        return;
      case LangPackage.INPUT__ENSURE_COMPONENTS:
        getEnsureComponents().clear();
        return;
      case LangPackage.INPUT__EXCLUDE_COMPONENTS:
        getExcludeComponents().clear();
        return;
      case LangPackage.INPUT__API_RULES:
        getApiRules().clear();
        return;
      case LangPackage.INPUT__DESTROY:
        setDestroy(DESTROY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case LangPackage.INPUT__UNQIUE:
        return unqiue != UNQIUE_EDEFAULT;
      case LangPackage.INPUT__TRIGGERS:
        return triggers != null && !triggers.isEmpty();
      case LangPackage.INPUT__ENSURE_COMPONENTS:
        return ensureComponents != null && !ensureComponents.isEmpty();
      case LangPackage.INPUT__EXCLUDE_COMPONENTS:
        return excludeComponents != null && !excludeComponents.isEmpty();
      case LangPackage.INPUT__API_RULES:
        return apiRules != null && !apiRules.isEmpty();
      case LangPackage.INPUT__DESTROY:
        return destroy != DESTROY_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (unqiue: ");
    result.append(unqiue);
    result.append(", destroy: ");
    result.append(destroy);
    result.append(')');
    return result.toString();
  }

} //InputImpl
