/*
 * generated by Xtext 2.10.0
 */
package ecs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLangScopeProvider extends DelegatingScopeProvider {
}
