/*
 * generated by Xtext 2.10.0
 */
package ecs.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class LangGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Project");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlatformDefinitionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPlatformDefinitionPlatformsParserRuleCall_0_0 = (RuleCall)cPlatformDefinitionAssignment_0.eContents().get(0);
		private final Assignment cNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNamespaceNamespaceParserRuleCall_1_0 = (RuleCall)cNamespaceAssignment_1.eContents().get(0);
		private final Assignment cTypeAliasesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeAliasesAliasParserRuleCall_2_0 = (RuleCall)cTypeAliasesAssignment_2.eContents().get(0);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Assignment cSystemsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSystemsSystemParserRuleCall_4_0 = (RuleCall)cSystemsAssignment_4.eContents().get(0);
		private final Assignment cParentSystemsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cParentSystemsParentSystemParserRuleCall_5_0 = (RuleCall)cParentSystemsAssignment_5.eContents().get(0);
		private final Assignment cContextDefinitionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cContextDefinitionsContextDefinitionParserRuleCall_6_0 = (RuleCall)cContextDefinitionsAssignment_6.eContents().get(0);
		
		//Project:
		//	platformDefinition=Platforms
		//	namespace=Namespace?
		//	typeAliases+=Alias*
		//	components+=Component*
		//	systems+=System*
		//	parentSystems+=ParentSystem*
		//	contextDefinitions+=ContextDefinition*;
		@Override public ParserRule getRule() { return rule; }
		
		//platformDefinition=Platforms namespace=Namespace? typeAliases+=Alias* components+=Component* systems+=System*
		//parentSystems+=ParentSystem* contextDefinitions+=ContextDefinition*
		public Group getGroup() { return cGroup; }
		
		//platformDefinition=Platforms
		public Assignment getPlatformDefinitionAssignment_0() { return cPlatformDefinitionAssignment_0; }
		
		//Platforms
		public RuleCall getPlatformDefinitionPlatformsParserRuleCall_0_0() { return cPlatformDefinitionPlatformsParserRuleCall_0_0; }
		
		//namespace=Namespace?
		public Assignment getNamespaceAssignment_1() { return cNamespaceAssignment_1; }
		
		//Namespace
		public RuleCall getNamespaceNamespaceParserRuleCall_1_0() { return cNamespaceNamespaceParserRuleCall_1_0; }
		
		//typeAliases+=Alias*
		public Assignment getTypeAliasesAssignment_2() { return cTypeAliasesAssignment_2; }
		
		//Alias
		public RuleCall getTypeAliasesAliasParserRuleCall_2_0() { return cTypeAliasesAliasParserRuleCall_2_0; }
		
		//components+=Component*
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//systems+=System*
		public Assignment getSystemsAssignment_4() { return cSystemsAssignment_4; }
		
		//System
		public RuleCall getSystemsSystemParserRuleCall_4_0() { return cSystemsSystemParserRuleCall_4_0; }
		
		//parentSystems+=ParentSystem*
		public Assignment getParentSystemsAssignment_5() { return cParentSystemsAssignment_5; }
		
		//ParentSystem
		public RuleCall getParentSystemsParentSystemParserRuleCall_5_0() { return cParentSystemsParentSystemParserRuleCall_5_0; }
		
		//contextDefinitions+=ContextDefinition*
		public Assignment getContextDefinitionsAssignment_6() { return cContextDefinitionsAssignment_6; }
		
		//ContextDefinition
		public RuleCall getContextDefinitionsContextDefinitionParserRuleCall_6_0() { return cContextDefinitionsContextDefinitionParserRuleCall_6_0; }
	}
	public class ContextDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ContextDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCtxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cComponentsAComponentCrossReference_3_0 = (CrossReference)cComponentsAssignment_3.eContents().get(0);
		private final RuleCall cComponentsAComponentIDTerminalRuleCall_3_0_1 = (RuleCall)cComponentsAComponentCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ContextDefinition:
		//	'ctx' name+=ValidID+ '{'
		//	components+=[AComponent]+
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ctx' name+=ValidID+ '{' components+=[AComponent]+ '}'
		public Group getGroup() { return cGroup; }
		
		//'ctx'
		public Keyword getCtxKeyword_0() { return cCtxKeyword_0; }
		
		//name+=ValidID+
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//components+=[AComponent]+
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//[AComponent]
		public CrossReference getComponentsAComponentCrossReference_3_0() { return cComponentsAComponentCrossReference_3_0; }
		
		//ID
		public RuleCall getComponentsAComponentIDTerminalRuleCall_3_0_1() { return cComponentsAComponentIDTerminalRuleCall_3_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PlatformsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Platforms");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPlatformKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdsPlatformIDParserRuleCall_1_0 = (RuleCall)cIdsAssignment_1.eContents().get(0);
		
		//Platforms:
		//	'platform' ids+=PlatformID+;
		@Override public ParserRule getRule() { return rule; }
		
		//'platform' ids+=PlatformID+
		public Group getGroup() { return cGroup; }
		
		//'platform'
		public Keyword getPlatformKeyword_0() { return cPlatformKeyword_0; }
		
		//ids+=PlatformID+
		public Assignment getIdsAssignment_1() { return cIdsAssignment_1; }
		
		//PlatformID
		public RuleCall getIdsPlatformIDParserRuleCall_1_0() { return cIdsPlatformIDParserRuleCall_1_0; }
	}
	public class PlatformIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.PlatformID");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//PlatformID:
		//	name=ValidID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ValidID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_0() { return cNameValidIDParserRuleCall_0; }
	}
	public class NamespaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Namespace");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNamespaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Namespace:
		//	"namespace" name=QualifiedName;
		@Override public ParserRule getRule() { return rule; }
		
		//"namespace" name=QualifiedName
		public Group getGroup() { return cGroup; }
		
		//"namespace"
		public Keyword getNamespaceKeyword_0() { return cNamespaceKeyword_0; }
		
		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }
	}
	public class AliasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Alias");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAliasKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cComponentAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cComponentAliasCompKeyword_1_0 = (Keyword)cComponentAliasAssignment_1.eContents().get(0);
		private final Assignment cUniqueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cUniqueUniqueKeyword_2_0 = (Keyword)cUniqueAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameValidIDParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cListOfAliasesAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cListOfAliasesAliasListParserRuleCall_4_0_0 = (RuleCall)cListOfAliasesAssignment_4_0.eContents().get(0);
		private final Assignment cSingleAliasAssignment_4_1 = (Assignment)cAlternatives_4.eContents().get(1);
		private final RuleCall cSingleAliasSingleAliasParserRuleCall_4_1_0 = (RuleCall)cSingleAliasAssignment_4_1.eContents().get(0);
		
		//Alias:
		//	'alias' componentAlias?='comp'? unique?='unique'? name=ValidID (listOfAliases=AliasList | singleAlias=SingleAlias);
		@Override public ParserRule getRule() { return rule; }
		
		//'alias' componentAlias?='comp'? unique?='unique'? name=ValidID (listOfAliases=AliasList | singleAlias=SingleAlias)
		public Group getGroup() { return cGroup; }
		
		//'alias'
		public Keyword getAliasKeyword_0() { return cAliasKeyword_0; }
		
		//componentAlias?='comp'?
		public Assignment getComponentAliasAssignment_1() { return cComponentAliasAssignment_1; }
		
		//'comp'
		public Keyword getComponentAliasCompKeyword_1_0() { return cComponentAliasCompKeyword_1_0; }
		
		//unique?='unique'?
		public Assignment getUniqueAssignment_2() { return cUniqueAssignment_2; }
		
		//'unique'
		public Keyword getUniqueUniqueKeyword_2_0() { return cUniqueUniqueKeyword_2_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_3_0() { return cNameValidIDParserRuleCall_3_0; }
		
		//(listOfAliases=AliasList | singleAlias=SingleAlias)
		public Alternatives getAlternatives_4() { return cAlternatives_4; }
		
		//listOfAliases=AliasList
		public Assignment getListOfAliasesAssignment_4_0() { return cListOfAliasesAssignment_4_0; }
		
		//AliasList
		public RuleCall getListOfAliasesAliasListParserRuleCall_4_0_0() { return cListOfAliasesAliasListParserRuleCall_4_0_0; }
		
		//singleAlias=SingleAlias
		public Assignment getSingleAliasAssignment_4_1() { return cSingleAliasAssignment_4_1; }
		
		//SingleAlias
		public RuleCall getSingleAliasSingleAliasParserRuleCall_4_1_0() { return cSingleAliasSingleAliasParserRuleCall_4_1_0; }
	}
	public class SingleAliasElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.SingleAlias");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEqualsSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeAliasSTRINGTerminalRuleCall_1_0 = (RuleCall)cTypeAliasAssignment_1.eContents().get(0);
		private final Assignment cSizeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSizeINTTerminalRuleCall_2_0 = (RuleCall)cSizeAssignment_2.eContents().get(0);
		
		//SingleAlias:
		//	'=' typeAlias=STRING size=INT?;
		@Override public ParserRule getRule() { return rule; }
		
		//'=' typeAlias=STRING size=INT?
		public Group getGroup() { return cGroup; }
		
		//'='
		public Keyword getEqualsSignKeyword_0() { return cEqualsSignKeyword_0; }
		
		//typeAlias=STRING
		public Assignment getTypeAliasAssignment_1() { return cTypeAliasAssignment_1; }
		
		//STRING
		public RuleCall getTypeAliasSTRINGTerminalRuleCall_1_0() { return cTypeAliasSTRINGTerminalRuleCall_1_0; }
		
		//size=INT?
		public Assignment getSizeAssignment_2() { return cSizeAssignment_2; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_2_0() { return cSizeINTTerminalRuleCall_2_0; }
	}
	public class AliasListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.AliasList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRulesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRulesAliasRuleParserRuleCall_1_0 = (RuleCall)cRulesAssignment_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//AliasList:
		//	'{' rules+=AliasRule+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'{' rules+=AliasRule+ '}'
		public Group getGroup() { return cGroup; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//rules+=AliasRule+
		public Assignment getRulesAssignment_1() { return cRulesAssignment_1; }
		
		//AliasRule
		public RuleCall getRulesAliasRuleParserRuleCall_1_0() { return cRulesAliasRuleParserRuleCall_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	public class AliasRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.AliasRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPlatformAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cPlatformPlatformIDCrossReference_0_0 = (CrossReference)cPlatformAssignment_0.eContents().get(0);
		private final RuleCall cPlatformPlatformIDIDTerminalRuleCall_0_0_1 = (RuleCall)cPlatformPlatformIDCrossReference_0_0.eContents().get(1);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAliasAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeAliasSTRINGTerminalRuleCall_2_0 = (RuleCall)cTypeAliasAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cSizeAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cSizeINTTerminalRuleCall_3_0_0 = (RuleCall)cSizeAssignment_3_0.eContents().get(0);
		private final Assignment cVariableSizeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final Keyword cVariableSizeAsteriskKeyword_3_1_0 = (Keyword)cVariableSizeAssignment_3_1.eContents().get(0);
		
		//AliasRule:
		//	platform=[PlatformID] ':' typeAlias=STRING (size=INT variableSize?='*'?)?;
		@Override public ParserRule getRule() { return rule; }
		
		//platform=[PlatformID] ':' typeAlias=STRING (size=INT variableSize?='*'?)?
		public Group getGroup() { return cGroup; }
		
		//platform=[PlatformID]
		public Assignment getPlatformAssignment_0() { return cPlatformAssignment_0; }
		
		//[PlatformID]
		public CrossReference getPlatformPlatformIDCrossReference_0_0() { return cPlatformPlatformIDCrossReference_0_0; }
		
		//ID
		public RuleCall getPlatformPlatformIDIDTerminalRuleCall_0_0_1() { return cPlatformPlatformIDIDTerminalRuleCall_0_0_1; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//typeAlias=STRING
		public Assignment getTypeAliasAssignment_2() { return cTypeAliasAssignment_2; }
		
		//STRING
		public RuleCall getTypeAliasSTRINGTerminalRuleCall_2_0() { return cTypeAliasSTRINGTerminalRuleCall_2_0; }
		
		//(size=INT variableSize?='*'?)?
		public Group getGroup_3() { return cGroup_3; }
		
		//size=INT
		public Assignment getSizeAssignment_3_0() { return cSizeAssignment_3_0; }
		
		//INT
		public RuleCall getSizeINTTerminalRuleCall_3_0_0() { return cSizeINTTerminalRuleCall_3_0_0; }
		
		//variableSize?='*'?
		public Assignment getVariableSizeAssignment_3_1() { return cVariableSizeAssignment_3_1; }
		
		//'*'
		public Keyword getVariableSizeAsteriskKeyword_3_1_0() { return cVariableSizeAsteriskKeyword_3_1_0; }
	}
	public class AComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.AComponent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cComponentParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAliasParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSystemParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cParentSystemParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//AComponent:
		//	Component | Alias | System | ParentSystem;
		@Override public ParserRule getRule() { return rule; }
		
		//Component | Alias | System | ParentSystem
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Component
		public RuleCall getComponentParserRuleCall_0() { return cComponentParserRuleCall_0; }
		
		//Alias
		public RuleCall getAliasParserRuleCall_1() { return cAliasParserRuleCall_1; }
		
		//System
		public RuleCall getSystemParserRuleCall_2() { return cSystemParserRuleCall_2; }
		
		//ParentSystem
		public RuleCall getParentSystemParserRuleCall_3() { return cParentSystemParserRuleCall_3; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Component");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUniqueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cUniqueUniqueKeyword_1_0 = (Keyword)cUniqueAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameValidIDParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_3_0 = (Alternatives)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_0_0 = (Group)cAlternatives_3_0.eContents().get(0);
		private final Keyword cColonKeyword_3_0_0_0 = (Keyword)cGroup_3_0_0.eContents().get(0);
		private final Assignment cValueTypeAssignment_3_0_0_1 = (Assignment)cGroup_3_0_0.eContents().get(1);
		private final CrossReference cValueTypeAliasCrossReference_3_0_0_1_0 = (CrossReference)cValueTypeAssignment_3_0_0_1.eContents().get(0);
		private final RuleCall cValueTypeAliasIDTerminalRuleCall_3_0_0_1_0_1 = (RuleCall)cValueTypeAliasCrossReference_3_0_0_1_0.eContents().get(1);
		private final Group cGroup_3_0_1 = (Group)cAlternatives_3_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3_0_1_0 = (Keyword)cGroup_3_0_1.eContents().get(0);
		private final Assignment cPropertiesAssignment_3_0_1_1 = (Assignment)cGroup_3_0_1.eContents().get(1);
		private final RuleCall cPropertiesComponentPropertyParserRuleCall_3_0_1_1_0 = (RuleCall)cPropertiesAssignment_3_0_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_0_1_2 = (Keyword)cGroup_3_0_1.eContents().get(2);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cSolidusKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Assignment cPrefixAssignment_3_1_1 = (Assignment)cGroup_3_1.eContents().get(1);
		private final RuleCall cPrefixSTRINGTerminalRuleCall_3_1_1_0 = (RuleCall)cPrefixAssignment_3_1_1.eContents().get(0);
		
		//Component:
		//	'comp' unique?='unique'? name=ValidID (((':' valueType=[Alias])? | '{' properties+=ComponentProperty+ '}') | '/'
		//	prefix=STRING);
		@Override public ParserRule getRule() { return rule; }
		
		//'comp' unique?='unique'? name=ValidID (((':' valueType=[Alias])? | '{' properties+=ComponentProperty+ '}') | '/'
		//prefix=STRING)
		public Group getGroup() { return cGroup; }
		
		//'comp'
		public Keyword getCompKeyword_0() { return cCompKeyword_0; }
		
		//unique?='unique'?
		public Assignment getUniqueAssignment_1() { return cUniqueAssignment_1; }
		
		//'unique'
		public Keyword getUniqueUniqueKeyword_1_0() { return cUniqueUniqueKeyword_1_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_2_0() { return cNameValidIDParserRuleCall_2_0; }
		
		//(((':' valueType=[Alias])? | '{' properties+=ComponentProperty+ '}') | '/' prefix=STRING)
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//((':' valueType=[Alias])? | '{' properties+=ComponentProperty+ '}')
		public Alternatives getAlternatives_3_0() { return cAlternatives_3_0; }
		
		//(':' valueType=[Alias])?
		public Group getGroup_3_0_0() { return cGroup_3_0_0; }
		
		//':'
		public Keyword getColonKeyword_3_0_0_0() { return cColonKeyword_3_0_0_0; }
		
		//valueType=[Alias]
		public Assignment getValueTypeAssignment_3_0_0_1() { return cValueTypeAssignment_3_0_0_1; }
		
		//[Alias]
		public CrossReference getValueTypeAliasCrossReference_3_0_0_1_0() { return cValueTypeAliasCrossReference_3_0_0_1_0; }
		
		//ID
		public RuleCall getValueTypeAliasIDTerminalRuleCall_3_0_0_1_0_1() { return cValueTypeAliasIDTerminalRuleCall_3_0_0_1_0_1; }
		
		//'{' properties+=ComponentProperty+ '}'
		public Group getGroup_3_0_1() { return cGroup_3_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_0_1_0() { return cLeftCurlyBracketKeyword_3_0_1_0; }
		
		//properties+=ComponentProperty+
		public Assignment getPropertiesAssignment_3_0_1_1() { return cPropertiesAssignment_3_0_1_1; }
		
		//ComponentProperty
		public RuleCall getPropertiesComponentPropertyParserRuleCall_3_0_1_1_0() { return cPropertiesComponentPropertyParserRuleCall_3_0_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_0_1_2() { return cRightCurlyBracketKeyword_3_0_1_2; }
		
		//'/' prefix=STRING
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'/'
		public Keyword getSolidusKeyword_3_1_0() { return cSolidusKeyword_3_1_0; }
		
		//prefix=STRING
		public Assignment getPrefixAssignment_3_1_1() { return cPrefixAssignment_3_1_1; }
		
		//STRING
		public RuleCall getPrefixSTRINGTerminalRuleCall_3_1_1_0() { return cPrefixSTRINGTerminalRuleCall_3_1_1_0; }
	}
	public class ComponentPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ComponentProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameValidIDParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTypeAliasCrossReference_2_0 = (CrossReference)cTypeAssignment_2.eContents().get(0);
		private final RuleCall cTypeAliasIDTerminalRuleCall_2_0_1 = (RuleCall)cTypeAliasCrossReference_2_0.eContents().get(1);
		
		//ComponentProperty:
		//	name=ValidID ':' type=[Alias];
		@Override public ParserRule getRule() { return rule; }
		
		//name=ValidID ':' type=[Alias]
		public Group getGroup() { return cGroup; }
		
		//name=ValidID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_0_0() { return cNameValidIDParserRuleCall_0_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=[Alias]
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//[Alias]
		public CrossReference getTypeAliasCrossReference_2_0() { return cTypeAliasCrossReference_2_0; }
		
		//ID
		public RuleCall getTypeAliasIDTerminalRuleCall_2_0_1() { return cTypeAliasIDTerminalRuleCall_2_0_1; }
	}
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSysKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cComponentAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cComponentAliasCompKeyword_1_0 = (Keyword)cComponentAliasAssignment_1.eContents().get(0);
		private final Assignment cUniqueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cUniqueUniqueKeyword_2_0 = (Keyword)cUniqueAssignment_2.eContents().get(0);
		private final Assignment cInitAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cInitInitKeyword_3_0 = (Keyword)cInitAssignment_3.eContents().get(0);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameValidIDParserRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cInputAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cInputInputParserRuleCall_6_0 = (RuleCall)cInputAssignment_6.eContents().get(0);
		private final Assignment cUniqueCompAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cUniqueCompUniqueComponentAccessParserRuleCall_7_0 = (RuleCall)cUniqueCompAssignment_7.eContents().get(0);
		private final Assignment cGroupsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cGroupsGroupParserRuleCall_8_0 = (RuleCall)cGroupsAssignment_8.eContents().get(0);
		private final Assignment cCreateRulesAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCreateRulesCreateRuleParserRuleCall_9_0 = (RuleCall)cCreateRulesAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//System:
		//	'sys' componentAlias?='comp'? unique?='unique'? init?='init'? name=ValidID '{'
		//	input=Input?
		//	uniqueComp+=UniqueComponentAccess*
		//	groups+=Group*
		//	createRules+=CreateRule*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'sys' componentAlias?='comp'? unique?='unique'? init?='init'? name=ValidID '{' input=Input?
		//uniqueComp+=UniqueComponentAccess* groups+=Group* createRules+=CreateRule* '}'
		public Group getGroup() { return cGroup; }
		
		//'sys'
		public Keyword getSysKeyword_0() { return cSysKeyword_0; }
		
		//componentAlias?='comp'?
		public Assignment getComponentAliasAssignment_1() { return cComponentAliasAssignment_1; }
		
		//'comp'
		public Keyword getComponentAliasCompKeyword_1_0() { return cComponentAliasCompKeyword_1_0; }
		
		//unique?='unique'?
		public Assignment getUniqueAssignment_2() { return cUniqueAssignment_2; }
		
		//'unique'
		public Keyword getUniqueUniqueKeyword_2_0() { return cUniqueUniqueKeyword_2_0; }
		
		//init?='init'?
		public Assignment getInitAssignment_3() { return cInitAssignment_3; }
		
		//'init'
		public Keyword getInitInitKeyword_3_0() { return cInitInitKeyword_3_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_4_0() { return cNameValidIDParserRuleCall_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//input=Input?
		public Assignment getInputAssignment_6() { return cInputAssignment_6; }
		
		//Input
		public RuleCall getInputInputParserRuleCall_6_0() { return cInputInputParserRuleCall_6_0; }
		
		//uniqueComp+=UniqueComponentAccess*
		public Assignment getUniqueCompAssignment_7() { return cUniqueCompAssignment_7; }
		
		//UniqueComponentAccess
		public RuleCall getUniqueCompUniqueComponentAccessParserRuleCall_7_0() { return cUniqueCompUniqueComponentAccessParserRuleCall_7_0; }
		
		//groups+=Group*
		public Assignment getGroupsAssignment_8() { return cGroupsAssignment_8; }
		
		//Group
		public RuleCall getGroupsGroupParserRuleCall_8_0() { return cGroupsGroupParserRuleCall_8_0; }
		
		//createRules+=CreateRule*
		public Assignment getCreateRulesAssignment_9() { return cCreateRulesAssignment_9; }
		
		//CreateRule
		public RuleCall getCreateRulesCreateRuleParserRuleCall_9_0() { return cCreateRulesCreateRuleParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class InputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Input");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInputKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUnqiueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cUnqiueUniqueKeyword_1_0 = (Keyword)cUnqiueAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTriggerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTriggersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTriggersInputTriggerParserRuleCall_5_0 = (RuleCall)cTriggersAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEnsureKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cColonKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cEnsureComponentsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cEnsureComponentsAComponentCrossReference_6_2_0 = (CrossReference)cEnsureComponentsAssignment_6_2.eContents().get(0);
		private final RuleCall cEnsureComponentsAComponentIDTerminalRuleCall_6_2_0_1 = (RuleCall)cEnsureComponentsAComponentCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cExcludeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cColonKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cExcludeComponentsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cExcludeComponentsAComponentCrossReference_7_2_0 = (CrossReference)cExcludeComponentsAssignment_7_2.eContents().get(0);
		private final RuleCall cExcludeComponentsAComponentIDTerminalRuleCall_7_2_0_1 = (RuleCall)cExcludeComponentsAComponentCrossReference_7_2_0.eContents().get(1);
		private final Keyword cApiKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cApiRulesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cApiRulesApiRuleParserRuleCall_10_0 = (RuleCall)cApiRulesAssignment_10.eContents().get(0);
		private final Assignment cDestroyAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final Keyword cDestroyDestroyKeyword_11_0 = (Keyword)cDestroyAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Input:
		//	'input' unqiue?='unique'? '{'
		//	'trigger' ':' triggers+=InputTrigger+ ('ensure' ':' ensureComponents+=[AComponent]+)? ('exclude' ':'
		//	excludeComponents+=[AComponent]+)?
		//	'api' ':' apiRules+=ApiRule+ destroy?='destroy'?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'input' unqiue?='unique'? '{' 'trigger' ':' triggers+=InputTrigger+ ('ensure' ':' ensureComponents+=[AComponent]+)?
		//('exclude' ':' excludeComponents+=[AComponent]+)? 'api' ':' apiRules+=ApiRule+ destroy?='destroy'? '}'
		public Group getGroup() { return cGroup; }
		
		//'input'
		public Keyword getInputKeyword_0() { return cInputKeyword_0; }
		
		//unqiue?='unique'?
		public Assignment getUnqiueAssignment_1() { return cUnqiueAssignment_1; }
		
		//'unique'
		public Keyword getUnqiueUniqueKeyword_1_0() { return cUnqiueUniqueKeyword_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'trigger'
		public Keyword getTriggerKeyword_3() { return cTriggerKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//triggers+=InputTrigger+
		public Assignment getTriggersAssignment_5() { return cTriggersAssignment_5; }
		
		//InputTrigger
		public RuleCall getTriggersInputTriggerParserRuleCall_5_0() { return cTriggersInputTriggerParserRuleCall_5_0; }
		
		//('ensure' ':' ensureComponents+=[AComponent]+)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'ensure'
		public Keyword getEnsureKeyword_6_0() { return cEnsureKeyword_6_0; }
		
		//':'
		public Keyword getColonKeyword_6_1() { return cColonKeyword_6_1; }
		
		//ensureComponents+=[AComponent]+
		public Assignment getEnsureComponentsAssignment_6_2() { return cEnsureComponentsAssignment_6_2; }
		
		//[AComponent]
		public CrossReference getEnsureComponentsAComponentCrossReference_6_2_0() { return cEnsureComponentsAComponentCrossReference_6_2_0; }
		
		//ID
		public RuleCall getEnsureComponentsAComponentIDTerminalRuleCall_6_2_0_1() { return cEnsureComponentsAComponentIDTerminalRuleCall_6_2_0_1; }
		
		//('exclude' ':' excludeComponents+=[AComponent]+)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'exclude'
		public Keyword getExcludeKeyword_7_0() { return cExcludeKeyword_7_0; }
		
		//':'
		public Keyword getColonKeyword_7_1() { return cColonKeyword_7_1; }
		
		//excludeComponents+=[AComponent]+
		public Assignment getExcludeComponentsAssignment_7_2() { return cExcludeComponentsAssignment_7_2; }
		
		//[AComponent]
		public CrossReference getExcludeComponentsAComponentCrossReference_7_2_0() { return cExcludeComponentsAComponentCrossReference_7_2_0; }
		
		//ID
		public RuleCall getExcludeComponentsAComponentIDTerminalRuleCall_7_2_0_1() { return cExcludeComponentsAComponentIDTerminalRuleCall_7_2_0_1; }
		
		//'api'
		public Keyword getApiKeyword_8() { return cApiKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//apiRules+=ApiRule+
		public Assignment getApiRulesAssignment_10() { return cApiRulesAssignment_10; }
		
		//ApiRule
		public RuleCall getApiRulesApiRuleParserRuleCall_10_0() { return cApiRulesApiRuleParserRuleCall_10_0; }
		
		//destroy?='destroy'?
		public Assignment getDestroyAssignment_11() { return cDestroyAssignment_11; }
		
		//'destroy'
		public Keyword getDestroyDestroyKeyword_11_0() { return cDestroyDestroyKeyword_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class InputTriggerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.InputTrigger");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cEnteredGroupKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cEnterComponentsAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final CrossReference cEnterComponentsAComponentCrossReference_0_2_0 = (CrossReference)cEnterComponentsAssignment_0_2.eContents().get(0);
		private final RuleCall cEnterComponentsAComponentIDTerminalRuleCall_0_2_0_1 = (RuleCall)cEnterComponentsAComponentCrossReference_0_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftGroupKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cLeftAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cLeftAComponentCrossReference_1_2_0 = (CrossReference)cLeftAssignment_1_2.eContents().get(0);
		private final RuleCall cLeftAComponentIDTerminalRuleCall_1_2_0_1 = (RuleCall)cLeftAComponentCrossReference_1_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cEnteredOrLeftGroupKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cEnteredOrLeftAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final CrossReference cEnteredOrLeftAComponentCrossReference_2_2_0 = (CrossReference)cEnteredOrLeftAssignment_2_2.eContents().get(0);
		private final RuleCall cEnteredOrLeftAComponentIDTerminalRuleCall_2_2_0_1 = (RuleCall)cEnteredOrLeftAComponentCrossReference_2_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//InputTrigger:
		//	'enteredGroup' '(' enterComponents+=[AComponent]+ ')' |
		//	'leftGroup' '(' left+=[AComponent]+ ')' |
		//	'enteredOrLeftGroup' '(' enteredOrLeft+=[AComponent]+ ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'enteredGroup' '(' enterComponents+=[AComponent]+ ')' | 'leftGroup' '(' left+=[AComponent]+ ')' | 'enteredOrLeftGroup'
		//'(' enteredOrLeft+=[AComponent]+ ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'enteredGroup' '(' enterComponents+=[AComponent]+ ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//'enteredGroup'
		public Keyword getEnteredGroupKeyword_0_0() { return cEnteredGroupKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//enterComponents+=[AComponent]+
		public Assignment getEnterComponentsAssignment_0_2() { return cEnterComponentsAssignment_0_2; }
		
		//[AComponent]
		public CrossReference getEnterComponentsAComponentCrossReference_0_2_0() { return cEnterComponentsAComponentCrossReference_0_2_0; }
		
		//ID
		public RuleCall getEnterComponentsAComponentIDTerminalRuleCall_0_2_0_1() { return cEnterComponentsAComponentIDTerminalRuleCall_0_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//'leftGroup' '(' left+=[AComponent]+ ')'
		public Group getGroup_1() { return cGroup_1; }
		
		//'leftGroup'
		public Keyword getLeftGroupKeyword_1_0() { return cLeftGroupKeyword_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1() { return cLeftParenthesisKeyword_1_1; }
		
		//left+=[AComponent]+
		public Assignment getLeftAssignment_1_2() { return cLeftAssignment_1_2; }
		
		//[AComponent]
		public CrossReference getLeftAComponentCrossReference_1_2_0() { return cLeftAComponentCrossReference_1_2_0; }
		
		//ID
		public RuleCall getLeftAComponentIDTerminalRuleCall_1_2_0_1() { return cLeftAComponentIDTerminalRuleCall_1_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_3() { return cRightParenthesisKeyword_1_3; }
		
		//'enteredOrLeftGroup' '(' enteredOrLeft+=[AComponent]+ ')'
		public Group getGroup_2() { return cGroup_2; }
		
		//'enteredOrLeftGroup'
		public Keyword getEnteredOrLeftGroupKeyword_2_0() { return cEnteredOrLeftGroupKeyword_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1() { return cLeftParenthesisKeyword_2_1; }
		
		//enteredOrLeft+=[AComponent]+
		public Assignment getEnteredOrLeftAssignment_2_2() { return cEnteredOrLeftAssignment_2_2; }
		
		//[AComponent]
		public CrossReference getEnteredOrLeftAComponentCrossReference_2_2_0() { return cEnteredOrLeftAComponentCrossReference_2_2_0; }
		
		//ID
		public RuleCall getEnteredOrLeftAComponentIDTerminalRuleCall_2_2_0_1() { return cEnteredOrLeftAComponentIDTerminalRuleCall_2_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_3() { return cRightParenthesisKeyword_2_3; }
	}
	public class CreateRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.CreateRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentTypesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cComponentTypesAComponentCrossReference_3_0 = (CrossReference)cComponentTypesAssignment_3.eContents().get(0);
		private final RuleCall cComponentTypesAComponentIDTerminalRuleCall_3_0_1 = (RuleCall)cComponentTypesAComponentCrossReference_3_0.eContents().get(1);
		
		//CreateRule:
		//	'create' name=ValidID ':' componentTypes+=[AComponent]+;
		@Override public ParserRule getRule() { return rule; }
		
		//'create' name=ValidID ':' componentTypes+=[AComponent]+
		public Group getGroup() { return cGroup; }
		
		//'create'
		public Keyword getCreateKeyword_0() { return cCreateKeyword_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//componentTypes+=[AComponent]+
		public Assignment getComponentTypesAssignment_3() { return cComponentTypesAssignment_3; }
		
		//[AComponent]
		public CrossReference getComponentTypesAComponentCrossReference_3_0() { return cComponentTypesAComponentCrossReference_3_0; }
		
		//ID
		public RuleCall getComponentTypesAComponentIDTerminalRuleCall_3_0_1() { return cComponentTypesAComponentIDTerminalRuleCall_3_0_1; }
	}
	public class UniqueComponentAccessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.UniqueComponentAccess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUniqueKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cApiRuleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cApiRuleApiRuleParserRuleCall_2_0 = (RuleCall)cApiRuleAssignment_2.eContents().get(0);
		
		//UniqueComponentAccess:
		//	'unique' ':' apiRule=ApiRule;
		@Override public ParserRule getRule() { return rule; }
		
		//'unique' ':' apiRule=ApiRule
		public Group getGroup() { return cGroup; }
		
		//'unique'
		public Keyword getUniqueKeyword_0() { return cUniqueKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//apiRule=ApiRule
		public Assignment getApiRuleAssignment_2() { return cApiRuleAssignment_2; }
		
		//ApiRule
		public RuleCall getApiRuleApiRuleParserRuleCall_2_0() { return cApiRuleApiRuleParserRuleCall_2_0; }
	}
	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Assignment cGroupAssignment_0_0 = (Assignment)cAlternatives_0.eContents().get(0);
		private final Keyword cGroupGroupKeyword_0_0_0 = (Keyword)cGroupAssignment_0_0.eContents().get(0);
		private final Assignment cUniqueAssignment_0_1 = (Assignment)cAlternatives_0.eContents().get(1);
		private final Keyword cUniqueUniqueKeyword_0_1_0 = (Keyword)cUniqueAssignment_0_1.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMatcherKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAllOfKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAllOfComponentsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cAllOfComponentsAComponentCrossReference_5_2_0 = (CrossReference)cAllOfComponentsAssignment_5_2.eContents().get(0);
		private final RuleCall cAllOfComponentsAComponentIDTerminalRuleCall_5_2_0_1 = (RuleCall)cAllOfComponentsAComponentCrossReference_5_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cAnyOfKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cAnyOfComponentsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cAnyOfComponentsAComponentCrossReference_6_2_0 = (CrossReference)cAnyOfComponentsAssignment_6_2.eContents().get(0);
		private final RuleCall cAnyOfComponentsAComponentIDTerminalRuleCall_6_2_0_1 = (RuleCall)cAnyOfComponentsAComponentCrossReference_6_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cNoneOfKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cNoneOfComponentsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cNoneOfComponentsAComponentCrossReference_7_2_0 = (CrossReference)cNoneOfComponentsAssignment_7_2.eContents().get(0);
		private final RuleCall cNoneOfComponentsAComponentIDTerminalRuleCall_7_2_0_1 = (RuleCall)cNoneOfComponentsAComponentCrossReference_7_2_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Keyword cApiKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cApiRulesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cApiRulesApiRuleParserRuleCall_10_0 = (RuleCall)cApiRulesAssignment_10.eContents().get(0);
		private final Assignment cDestroyAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final Keyword cDestroyDestroyKeyword_11_0 = (Keyword)cDestroyAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Group:
		//	(group?='group' | unique?='unique') name=ValidID '{'
		//	'matcher' ':' ('allOf' '(' allOfComponents+=[AComponent]+ ')')? ('anyOf' '(' anyOfComponents+=[AComponent]+ ')')?
		//	('noneOf' '(' noneOfComponents+=[AComponent]+ ')')?
		//	'api' ':' apiRules+=ApiRule+ destroy?='destroy'?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//(group?='group' | unique?='unique') name=ValidID '{' 'matcher' ':' ('allOf' '(' allOfComponents+=[AComponent]+ ')')?
		//('anyOf' '(' anyOfComponents+=[AComponent]+ ')')? ('noneOf' '(' noneOfComponents+=[AComponent]+ ')')? 'api' ':'
		//apiRules+=ApiRule+ destroy?='destroy'? '}'
		public Group getGroup() { return cGroup; }
		
		//(group?='group' | unique?='unique')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//group?='group'
		public Assignment getGroupAssignment_0_0() { return cGroupAssignment_0_0; }
		
		//'group'
		public Keyword getGroupGroupKeyword_0_0_0() { return cGroupGroupKeyword_0_0_0; }
		
		//unique?='unique'
		public Assignment getUniqueAssignment_0_1() { return cUniqueAssignment_0_1; }
		
		//'unique'
		public Keyword getUniqueUniqueKeyword_0_1_0() { return cUniqueUniqueKeyword_0_1_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'matcher'
		public Keyword getMatcherKeyword_3() { return cMatcherKeyword_3; }
		
		//':'
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//('allOf' '(' allOfComponents+=[AComponent]+ ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'allOf'
		public Keyword getAllOfKeyword_5_0() { return cAllOfKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//allOfComponents+=[AComponent]+
		public Assignment getAllOfComponentsAssignment_5_2() { return cAllOfComponentsAssignment_5_2; }
		
		//[AComponent]
		public CrossReference getAllOfComponentsAComponentCrossReference_5_2_0() { return cAllOfComponentsAComponentCrossReference_5_2_0; }
		
		//ID
		public RuleCall getAllOfComponentsAComponentIDTerminalRuleCall_5_2_0_1() { return cAllOfComponentsAComponentIDTerminalRuleCall_5_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_3() { return cRightParenthesisKeyword_5_3; }
		
		//('anyOf' '(' anyOfComponents+=[AComponent]+ ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'anyOf'
		public Keyword getAnyOfKeyword_6_0() { return cAnyOfKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//anyOfComponents+=[AComponent]+
		public Assignment getAnyOfComponentsAssignment_6_2() { return cAnyOfComponentsAssignment_6_2; }
		
		//[AComponent]
		public CrossReference getAnyOfComponentsAComponentCrossReference_6_2_0() { return cAnyOfComponentsAComponentCrossReference_6_2_0; }
		
		//ID
		public RuleCall getAnyOfComponentsAComponentIDTerminalRuleCall_6_2_0_1() { return cAnyOfComponentsAComponentIDTerminalRuleCall_6_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_3() { return cRightParenthesisKeyword_6_3; }
		
		//('noneOf' '(' noneOfComponents+=[AComponent]+ ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'noneOf'
		public Keyword getNoneOfKeyword_7_0() { return cNoneOfKeyword_7_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_1() { return cLeftParenthesisKeyword_7_1; }
		
		//noneOfComponents+=[AComponent]+
		public Assignment getNoneOfComponentsAssignment_7_2() { return cNoneOfComponentsAssignment_7_2; }
		
		//[AComponent]
		public CrossReference getNoneOfComponentsAComponentCrossReference_7_2_0() { return cNoneOfComponentsAComponentCrossReference_7_2_0; }
		
		//ID
		public RuleCall getNoneOfComponentsAComponentIDTerminalRuleCall_7_2_0_1() { return cNoneOfComponentsAComponentIDTerminalRuleCall_7_2_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_3() { return cRightParenthesisKeyword_7_3; }
		
		//'api'
		public Keyword getApiKeyword_8() { return cApiKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//apiRules+=ApiRule+
		public Assignment getApiRulesAssignment_10() { return cApiRulesAssignment_10; }
		
		//ApiRule
		public RuleCall getApiRulesApiRuleParserRuleCall_10_0() { return cApiRulesApiRuleParserRuleCall_10_0; }
		
		//destroy?='destroy'?
		public Assignment getDestroyAssignment_11() { return cDestroyAssignment_11; }
		
		//'destroy'
		public Keyword getDestroyDestroyKeyword_11_0() { return cDestroyDestroyKeyword_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class ApiRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ApiRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComponentAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cComponentAComponentCrossReference_0_0 = (CrossReference)cComponentAssignment_0.eContents().get(0);
		private final RuleCall cComponentAComponentIDTerminalRuleCall_0_0_1 = (RuleCall)cComponentAComponentCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cAccesorsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cAccesorsComponentApiAccessorParserRuleCall_1_1_0 = (RuleCall)cAccesorsAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//ApiRule:
		//	component=[AComponent] ('(' accesors+=ComponentApiAccessor+ ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//component=[AComponent] ('(' accesors+=ComponentApiAccessor+ ')')?
		public Group getGroup() { return cGroup; }
		
		//component=[AComponent]
		public Assignment getComponentAssignment_0() { return cComponentAssignment_0; }
		
		//[AComponent]
		public CrossReference getComponentAComponentCrossReference_0_0() { return cComponentAComponentCrossReference_0_0; }
		
		//ID
		public RuleCall getComponentAComponentIDTerminalRuleCall_0_0_1() { return cComponentAComponentIDTerminalRuleCall_0_0_1; }
		
		//('(' accesors+=ComponentApiAccessor+ ')')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//accesors+=ComponentApiAccessor+
		public Assignment getAccesorsAssignment_1_1() { return cAccesorsAssignment_1_1; }
		
		//ComponentApiAccessor
		public RuleCall getAccesorsComponentApiAccessorParserRuleCall_1_1_0() { return cAccesorsComponentApiAccessorParserRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class ComponentApiAccessorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ComponentApiAccessor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cAddKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cGetKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cHasKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cReplaceKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cRemoveKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//ComponentApiAccessor:
		//	'add' | 'get' | 'has' | 'replace' | 'remove';
		@Override public ParserRule getRule() { return rule; }
		
		//'add' | 'get' | 'has' | 'replace' | 'remove'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'add'
		public Keyword getAddKeyword_0() { return cAddKeyword_0; }
		
		//'get'
		public Keyword getGetKeyword_1() { return cGetKeyword_1; }
		
		//'has'
		public Keyword getHasKeyword_2() { return cHasKeyword_2; }
		
		//'replace'
		public Keyword getReplaceKeyword_3() { return cReplaceKeyword_3; }
		
		//'remove'
		public Keyword getRemoveKeyword_4() { return cRemoveKeyword_4; }
	}
	public class ASystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ASystem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSystemParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParentSystemParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ASystem:
		//	System | ParentSystem;
		@Override public ParserRule getRule() { return rule; }
		
		//System | ParentSystem
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//System
		public RuleCall getSystemParserRuleCall_0() { return cSystemParserRuleCall_0; }
		
		//ParentSystem
		public RuleCall getParentSystemParserRuleCall_1() { return cParentSystemParserRuleCall_1; }
	}
	public class ParentSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ParentSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParent_sysKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cComponentAliasAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cComponentAliasCompKeyword_1_0 = (Keyword)cComponentAliasAssignment_1.eContents().get(0);
		private final Assignment cUniqueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cUniqueUniqueKeyword_2_0 = (Keyword)cUniqueAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameValidIDParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cExtendsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cParentAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cParentAliasCrossReference_4_1_0 = (CrossReference)cParentAssignment_4_1.eContents().get(0);
		private final RuleCall cParentAliasIDTerminalRuleCall_4_1_0_1 = (RuleCall)cParentAliasCrossReference_4_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cChildrenAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cChildrenASystemCrossReference_6_0 = (CrossReference)cChildrenAssignment_6.eContents().get(0);
		private final RuleCall cChildrenASystemIDTerminalRuleCall_6_0_1 = (RuleCall)cChildrenASystemCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ParentSystem:
		//	'parent_sys' componentAlias?='comp'? unique?='unique'? name=ValidID ('extends' parent=[Alias])? '{'
		//	children+=[ASystem]+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'parent_sys' componentAlias?='comp'? unique?='unique'? name=ValidID ('extends' parent=[Alias])? '{' children+=[ASystem]+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'parent_sys'
		public Keyword getParent_sysKeyword_0() { return cParent_sysKeyword_0; }
		
		//componentAlias?='comp'?
		public Assignment getComponentAliasAssignment_1() { return cComponentAliasAssignment_1; }
		
		//'comp'
		public Keyword getComponentAliasCompKeyword_1_0() { return cComponentAliasCompKeyword_1_0; }
		
		//unique?='unique'?
		public Assignment getUniqueAssignment_2() { return cUniqueAssignment_2; }
		
		//'unique'
		public Keyword getUniqueUniqueKeyword_2_0() { return cUniqueUniqueKeyword_2_0; }
		
		//name=ValidID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ValidID
		public RuleCall getNameValidIDParserRuleCall_3_0() { return cNameValidIDParserRuleCall_3_0; }
		
		//('extends' parent=[Alias])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'extends'
		public Keyword getExtendsKeyword_4_0() { return cExtendsKeyword_4_0; }
		
		//parent=[Alias]
		public Assignment getParentAssignment_4_1() { return cParentAssignment_4_1; }
		
		//[Alias]
		public CrossReference getParentAliasCrossReference_4_1_0() { return cParentAliasCrossReference_4_1_0; }
		
		//ID
		public RuleCall getParentAliasIDTerminalRuleCall_4_1_0_1() { return cParentAliasIDTerminalRuleCall_4_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//children+=[ASystem]+
		public Assignment getChildrenAssignment_6() { return cChildrenAssignment_6; }
		
		//[ASystem]
		public CrossReference getChildrenASystemCrossReference_6_0() { return cChildrenASystemCrossReference_6_0; }
		
		//ID
		public RuleCall getChildrenASystemIDTerminalRuleCall_6_0_1() { return cChildrenASystemIDTerminalRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cValidIDParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cValidIDParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ValidID ('.' ValidID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ValidID ('.' ValidID)*
		public Group getGroup() { return cGroup; }
		
		//ValidID
		public RuleCall getValidIDParserRuleCall_0() { return cValidIDParserRuleCall_0; }
		
		//('.' ValidID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ValidID
		public RuleCall getValidIDParserRuleCall_1_1() { return cValidIDParserRuleCall_1_1; }
	}
	public class ValidIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ecs.Lang.ValidID");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ValidID:
		//	ID;
		@Override public ParserRule getRule() { return rule; }
		
		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}
	
	
	private final ProjectElements pProject;
	private final ContextDefinitionElements pContextDefinition;
	private final PlatformsElements pPlatforms;
	private final PlatformIDElements pPlatformID;
	private final NamespaceElements pNamespace;
	private final AliasElements pAlias;
	private final SingleAliasElements pSingleAlias;
	private final AliasListElements pAliasList;
	private final AliasRuleElements pAliasRule;
	private final AComponentElements pAComponent;
	private final ComponentElements pComponent;
	private final ComponentPropertyElements pComponentProperty;
	private final SystemElements pSystem;
	private final InputElements pInput;
	private final InputTriggerElements pInputTrigger;
	private final CreateRuleElements pCreateRule;
	private final UniqueComponentAccessElements pUniqueComponentAccess;
	private final GroupElements pGroup;
	private final ApiRuleElements pApiRule;
	private final ComponentApiAccessorElements pComponentApiAccessor;
	private final ASystemElements pASystem;
	private final ParentSystemElements pParentSystem;
	private final QualifiedNameElements pQualifiedName;
	private final ValidIDElements pValidID;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public LangGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProject = new ProjectElements();
		this.pContextDefinition = new ContextDefinitionElements();
		this.pPlatforms = new PlatformsElements();
		this.pPlatformID = new PlatformIDElements();
		this.pNamespace = new NamespaceElements();
		this.pAlias = new AliasElements();
		this.pSingleAlias = new SingleAliasElements();
		this.pAliasList = new AliasListElements();
		this.pAliasRule = new AliasRuleElements();
		this.pAComponent = new AComponentElements();
		this.pComponent = new ComponentElements();
		this.pComponentProperty = new ComponentPropertyElements();
		this.pSystem = new SystemElements();
		this.pInput = new InputElements();
		this.pInputTrigger = new InputTriggerElements();
		this.pCreateRule = new CreateRuleElements();
		this.pUniqueComponentAccess = new UniqueComponentAccessElements();
		this.pGroup = new GroupElements();
		this.pApiRule = new ApiRuleElements();
		this.pComponentApiAccessor = new ComponentApiAccessorElements();
		this.pASystem = new ASystemElements();
		this.pParentSystem = new ParentSystemElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pValidID = new ValidIDElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("ecs.Lang".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Project:
	//	platformDefinition=Platforms
	//	namespace=Namespace?
	//	typeAliases+=Alias*
	//	components+=Component*
	//	systems+=System*
	//	parentSystems+=ParentSystem*
	//	contextDefinitions+=ContextDefinition*;
	public ProjectElements getProjectAccess() {
		return pProject;
	}
	
	public ParserRule getProjectRule() {
		return getProjectAccess().getRule();
	}
	
	//ContextDefinition:
	//	'ctx' name+=ValidID+ '{'
	//	components+=[AComponent]+
	//	'}';
	public ContextDefinitionElements getContextDefinitionAccess() {
		return pContextDefinition;
	}
	
	public ParserRule getContextDefinitionRule() {
		return getContextDefinitionAccess().getRule();
	}
	
	//Platforms:
	//	'platform' ids+=PlatformID+;
	public PlatformsElements getPlatformsAccess() {
		return pPlatforms;
	}
	
	public ParserRule getPlatformsRule() {
		return getPlatformsAccess().getRule();
	}
	
	//PlatformID:
	//	name=ValidID;
	public PlatformIDElements getPlatformIDAccess() {
		return pPlatformID;
	}
	
	public ParserRule getPlatformIDRule() {
		return getPlatformIDAccess().getRule();
	}
	
	//Namespace:
	//	"namespace" name=QualifiedName;
	public NamespaceElements getNamespaceAccess() {
		return pNamespace;
	}
	
	public ParserRule getNamespaceRule() {
		return getNamespaceAccess().getRule();
	}
	
	//Alias:
	//	'alias' componentAlias?='comp'? unique?='unique'? name=ValidID (listOfAliases=AliasList | singleAlias=SingleAlias);
	public AliasElements getAliasAccess() {
		return pAlias;
	}
	
	public ParserRule getAliasRule() {
		return getAliasAccess().getRule();
	}
	
	//SingleAlias:
	//	'=' typeAlias=STRING size=INT?;
	public SingleAliasElements getSingleAliasAccess() {
		return pSingleAlias;
	}
	
	public ParserRule getSingleAliasRule() {
		return getSingleAliasAccess().getRule();
	}
	
	//AliasList:
	//	'{' rules+=AliasRule+ '}';
	public AliasListElements getAliasListAccess() {
		return pAliasList;
	}
	
	public ParserRule getAliasListRule() {
		return getAliasListAccess().getRule();
	}
	
	//AliasRule:
	//	platform=[PlatformID] ':' typeAlias=STRING (size=INT variableSize?='*'?)?;
	public AliasRuleElements getAliasRuleAccess() {
		return pAliasRule;
	}
	
	public ParserRule getAliasRuleRule() {
		return getAliasRuleAccess().getRule();
	}
	
	//AComponent:
	//	Component | Alias | System | ParentSystem;
	public AComponentElements getAComponentAccess() {
		return pAComponent;
	}
	
	public ParserRule getAComponentRule() {
		return getAComponentAccess().getRule();
	}
	
	//Component:
	//	'comp' unique?='unique'? name=ValidID (((':' valueType=[Alias])? | '{' properties+=ComponentProperty+ '}') | '/'
	//	prefix=STRING);
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//ComponentProperty:
	//	name=ValidID ':' type=[Alias];
	public ComponentPropertyElements getComponentPropertyAccess() {
		return pComponentProperty;
	}
	
	public ParserRule getComponentPropertyRule() {
		return getComponentPropertyAccess().getRule();
	}
	
	//System:
	//	'sys' componentAlias?='comp'? unique?='unique'? init?='init'? name=ValidID '{'
	//	input=Input?
	//	uniqueComp+=UniqueComponentAccess*
	//	groups+=Group*
	//	createRules+=CreateRule*
	//	'}';
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//Input:
	//	'input' unqiue?='unique'? '{'
	//	'trigger' ':' triggers+=InputTrigger+ ('ensure' ':' ensureComponents+=[AComponent]+)? ('exclude' ':'
	//	excludeComponents+=[AComponent]+)?
	//	'api' ':' apiRules+=ApiRule+ destroy?='destroy'?
	//	'}';
	public InputElements getInputAccess() {
		return pInput;
	}
	
	public ParserRule getInputRule() {
		return getInputAccess().getRule();
	}
	
	//InputTrigger:
	//	'enteredGroup' '(' enterComponents+=[AComponent]+ ')' |
	//	'leftGroup' '(' left+=[AComponent]+ ')' |
	//	'enteredOrLeftGroup' '(' enteredOrLeft+=[AComponent]+ ')';
	public InputTriggerElements getInputTriggerAccess() {
		return pInputTrigger;
	}
	
	public ParserRule getInputTriggerRule() {
		return getInputTriggerAccess().getRule();
	}
	
	//CreateRule:
	//	'create' name=ValidID ':' componentTypes+=[AComponent]+;
	public CreateRuleElements getCreateRuleAccess() {
		return pCreateRule;
	}
	
	public ParserRule getCreateRuleRule() {
		return getCreateRuleAccess().getRule();
	}
	
	//UniqueComponentAccess:
	//	'unique' ':' apiRule=ApiRule;
	public UniqueComponentAccessElements getUniqueComponentAccessAccess() {
		return pUniqueComponentAccess;
	}
	
	public ParserRule getUniqueComponentAccessRule() {
		return getUniqueComponentAccessAccess().getRule();
	}
	
	//Group:
	//	(group?='group' | unique?='unique') name=ValidID '{'
	//	'matcher' ':' ('allOf' '(' allOfComponents+=[AComponent]+ ')')? ('anyOf' '(' anyOfComponents+=[AComponent]+ ')')?
	//	('noneOf' '(' noneOfComponents+=[AComponent]+ ')')?
	//	'api' ':' apiRules+=ApiRule+ destroy?='destroy'?
	//	'}';
	public GroupElements getGroupAccess() {
		return pGroup;
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}
	
	//ApiRule:
	//	component=[AComponent] ('(' accesors+=ComponentApiAccessor+ ')')?;
	public ApiRuleElements getApiRuleAccess() {
		return pApiRule;
	}
	
	public ParserRule getApiRuleRule() {
		return getApiRuleAccess().getRule();
	}
	
	//ComponentApiAccessor:
	//	'add' | 'get' | 'has' | 'replace' | 'remove';
	public ComponentApiAccessorElements getComponentApiAccessorAccess() {
		return pComponentApiAccessor;
	}
	
	public ParserRule getComponentApiAccessorRule() {
		return getComponentApiAccessorAccess().getRule();
	}
	
	//ASystem:
	//	System | ParentSystem;
	public ASystemElements getASystemAccess() {
		return pASystem;
	}
	
	public ParserRule getASystemRule() {
		return getASystemAccess().getRule();
	}
	
	//ParentSystem:
	//	'parent_sys' componentAlias?='comp'? unique?='unique'? name=ValidID ('extends' parent=[Alias])? '{'
	//	children+=[ASystem]+ '}';
	public ParentSystemElements getParentSystemAccess() {
		return pParentSystem;
	}
	
	public ParserRule getParentSystemRule() {
		return getParentSystemAccess().getRule();
	}
	
	//QualifiedName:
	//	ValidID ('.' ValidID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//ValidID:
	//	ID;
	public ValidIDElements getValidIDAccess() {
		return pValidID;
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
