/*
 * generated by Xtext 2.10.0
 */
package ecs.ui.tests;

import com.google.inject.Injector;
import ecs.lang.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class LangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorActivator.getInstance().getInjector("ecs.Lang");
	}

}
